### ISSUE TITLE
Pick design

### ISSUE THREAD

**Issue by FrolickingMustelid** [Hack-Weekly/crimson-eagle-sudoku#2]

**Comment by cmedina-dev** [comment]
I think a flat color scheme and design would work well here since Sudoku is a very minimalist UI.
Here's a site with some nice Sudoku UI designs:
https://dribbble.com/tags/sudoku?page=

**Comment by FrolickingMustelid** [comment]
Check [Algorithms: UI](https://discord.com/channels/1082086126954758174/1138784969678913556), I've put some examples there that I liked. You can add your picks or vote on those you like best.
